package TugasAkhir;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kresn
 */
public class bookrent extends javax.swing.JFrame {

    /**
     * Creates new form bookrent
     */
    public bookrent() {
        initComponents();  
        setTitle("MANGAZONE");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInti = new javax.swing.JPanel();
        pnlCaraBayar = new javax.swing.JPanel();
        lblCaraBayar = new javax.swing.JLabel();
        rdbGopay = new javax.swing.JRadioButton();
        rdbDebit = new javax.swing.JRadioButton();
        rdbCash = new javax.swing.JRadioButton();
        pnlMenu = new javax.swing.JPanel();
        lblNamaProgram = new javax.swing.JLabel();
        txtHorimiya = new javax.swing.JTextField();
        txtKimetsunoYaiba = new javax.swing.JTextField();
        txtShingekinoKyojin = new javax.swing.JTextField();
        lblJudul = new javax.swing.JLabel();
        lblHari = new javax.swing.JLabel();
        chkJujutsuKaisen = new javax.swing.JCheckBox();
        chkHorimiya = new javax.swing.JCheckBox();
        chkKimetsunoYaiba = new javax.swing.JCheckBox();
        chkShingekinoKyojin = new javax.swing.JCheckBox();
        txtJujutsuKaisen = new javax.swing.JTextField();
        chkBNHA = new javax.swing.JCheckBox();
        chkKemonoJihen = new javax.swing.JCheckBox();
        chkGakuenBabysitter = new javax.swing.JCheckBox();
        chkHaikyuu = new javax.swing.JCheckBox();
        txtBNHA = new javax.swing.JTextField();
        txtKemonoJihen = new javax.swing.JTextField();
        txtGakuenBabysitter = new javax.swing.JTextField();
        txtHaikyuu = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblBayar0 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(128, 128, 128));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlInti.setBackground(new java.awt.Color(234, 222, 241));

        pnlCaraBayar.setBackground(new java.awt.Color(234, 222, 241));

        lblCaraBayar.setFont(new java.awt.Font("Roboto Cn", 1, 12)); // NOI18N
        lblCaraBayar.setText("Pay with");

        rdbGopay.setBackground(new java.awt.Color(234, 222, 241));
        rdbGopay.setText("Gopay");
        rdbGopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbGopayActionPerformed(evt);
            }
        });

        rdbDebit.setBackground(new java.awt.Color(234, 222, 241));
        rdbDebit.setText("Debit");
        rdbDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDebitActionPerformed(evt);
            }
        });

        rdbCash.setBackground(new java.awt.Color(234, 222, 241));
        rdbCash.setText("Cash");
        rdbCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCaraBayarLayout = new javax.swing.GroupLayout(pnlCaraBayar);
        pnlCaraBayar.setLayout(pnlCaraBayarLayout);
        pnlCaraBayarLayout.setHorizontalGroup(
            pnlCaraBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaraBayarLayout.createSequentialGroup()
                .addGroup(pnlCaraBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbCash)
                    .addComponent(rdbDebit)
                    .addComponent(rdbGopay)
                    .addComponent(lblCaraBayar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCaraBayarLayout.setVerticalGroup(
            pnlCaraBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaraBayarLayout.createSequentialGroup()
                .addComponent(lblCaraBayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbGopay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbDebit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbCash)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(234, 222, 241));

        lblNamaProgram.setBackground(new java.awt.Color(79, 155, 91));
        lblNamaProgram.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblNamaProgram.setForeground(new java.awt.Color(0, 153, 51));
        lblNamaProgram.setText("Mangazone Book Rent");

        txtHorimiya.setText("0");
        txtHorimiya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorimiyaActionPerformed(evt);
            }
        });

        txtKimetsunoYaiba.setText("0");
        txtKimetsunoYaiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKimetsunoYaibaActionPerformed(evt);
            }
        });

        txtShingekinoKyojin.setText("0");
        txtShingekinoKyojin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShingekinoKyojinActionPerformed(evt);
            }
        });

        lblJudul.setFont(new java.awt.Font("Roboto Cn", 1, 12)); // NOI18N
        lblJudul.setText("Title");

        lblHari.setFont(new java.awt.Font("Roboto Cn", 1, 12)); // NOI18N
        lblHari.setText("Many days for rent");

        chkJujutsuKaisen.setBackground(new java.awt.Color(234, 222, 241));
        chkJujutsuKaisen.setText("Jujutsu Kaisen");
        chkJujutsuKaisen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJujutsuKaisenActionPerformed(evt);
            }
        });

        chkHorimiya.setBackground(new java.awt.Color(234, 222, 241));
        chkHorimiya.setText("Horimiya");
        chkHorimiya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHorimiyaActionPerformed(evt);
            }
        });

        chkKimetsunoYaiba.setBackground(new java.awt.Color(234, 222, 241));
        chkKimetsunoYaiba.setText("Kimetsu no Yaiba");
        chkKimetsunoYaiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKimetsunoYaibaActionPerformed(evt);
            }
        });

        chkShingekinoKyojin.setBackground(new java.awt.Color(234, 222, 241));
        chkShingekinoKyojin.setText("Shingeki no Kyojin");
        chkShingekinoKyojin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShingekinoKyojinActionPerformed(evt);
            }
        });

        txtJujutsuKaisen.setText("0");
        txtJujutsuKaisen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJujutsuKaisenActionPerformed(evt);
            }
        });

        chkBNHA.setBackground(new java.awt.Color(234, 222, 241));
        chkBNHA.setText("Boku no Hero Academia");
        chkBNHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBNHAActionPerformed(evt);
            }
        });

        chkKemonoJihen.setBackground(new java.awt.Color(234, 222, 241));
        chkKemonoJihen.setText("Kemono Jihen");
        chkKemonoJihen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKemonoJihenActionPerformed(evt);
            }
        });

        chkGakuenBabysitter.setBackground(new java.awt.Color(234, 222, 241));
        chkGakuenBabysitter.setText("Gakuen Babysitter");
        chkGakuenBabysitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGakuenBabysitterActionPerformed(evt);
            }
        });

        chkHaikyuu.setBackground(new java.awt.Color(234, 222, 241));
        chkHaikyuu.setText("Haikyuu");
        chkHaikyuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHaikyuuActionPerformed(evt);
            }
        });

        txtBNHA.setText("0");
        txtBNHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBNHAActionPerformed(evt);
            }
        });

        txtKemonoJihen.setText("0");
        txtKemonoJihen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKemonoJihenActionPerformed(evt);
            }
        });

        txtGakuenBabysitter.setText("0");
        txtGakuenBabysitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGakuenBabysitterActionPerformed(evt);
            }
        });

        txtHaikyuu.setText("0");
        txtHaikyuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHaikyuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkShingekinoKyojin)
                            .addComponent(chkKimetsunoYaiba)
                            .addComponent(lblJudul)
                            .addComponent(chkHorimiya)
                            .addComponent(chkJujutsuKaisen)
                            .addComponent(chkHaikyuu)
                            .addComponent(chkKemonoJihen)
                            .addComponent(chkBNHA)
                            .addComponent(chkGakuenBabysitter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJujutsuKaisen)
                            .addComponent(txtHorimiya)
                            .addComponent(txtKimetsunoYaiba)
                            .addComponent(txtShingekinoKyojin)
                            .addComponent(txtBNHA)
                            .addComponent(txtKemonoJihen)
                            .addComponent(txtGakuenBabysitter)
                            .addComponent(txtHaikyuu)))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(lblNamaProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(lblNamaProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHari)
                    .addComponent(lblJudul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkJujutsuKaisen)
                    .addComponent(txtJujutsuKaisen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHorimiya)
                    .addComponent(txtHorimiya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkKimetsunoYaiba)
                    .addComponent(txtKimetsunoYaiba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkShingekinoKyojin)
                    .addComponent(txtShingekinoKyojin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBNHA)
                    .addComponent(txtBNHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkKemonoJihen)
                    .addComponent(txtKemonoJihen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkGakuenBabysitter)
                    .addComponent(txtGakuenBabysitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHaikyuu)
                    .addComponent(txtHaikyuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnSubmit.setBackground(new java.awt.Color(239, 160, 160));
        btnSubmit.setFont(new java.awt.Font("Helvetica", 1, 11)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblBayar0.setText("Rp. 0");

        btnClear.setBackground(new java.awt.Color(98, 106, 204));
        btnClear.setFont(new java.awt.Font("Helvetica", 1, 11)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIntiLayout = new javax.swing.GroupLayout(pnlInti);
        pnlInti.setLayout(pnlIntiLayout);
        pnlIntiLayout.setHorizontalGroup(
            pnlIntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntiLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlIntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIntiLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(pnlCaraBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlIntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBayar0)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        pnlIntiLayout.setVerticalGroup(
            pnlIntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntiLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCaraBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlIntiLayout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBayar0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlInti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtJujutsuKaisenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJujutsuKaisenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJujutsuKaisenActionPerformed

    private void chkHorimiyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHorimiyaActionPerformed
        // TODO add your handling code here:
        if(chkHorimiya.isSelected()){
            txtHorimiya.setEditable(true);
            txtHorimiya.setText("1");
        } else{
          txtHorimiya.setEditable(false);
          txtHorimiya.setText("0");
        }
    }//GEN-LAST:event_chkHorimiyaActionPerformed

    private void chkJujutsuKaisenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJujutsuKaisenActionPerformed
        // TODO add your handling code here:
        if(chkJujutsuKaisen.isSelected()){
            txtJujutsuKaisen.setEditable(true);
            txtJujutsuKaisen.setText("1");
        } else{
          txtJujutsuKaisen.setEditable(false);
          txtJujutsuKaisen.setText("0");
        }
    }//GEN-LAST:event_chkJujutsuKaisenActionPerformed

       
    private void txtShingekinoKyojinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShingekinoKyojinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShingekinoKyojinActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        int btnClear = JOptionPane.showConfirmDialog(null, "Are you sure to clear it?", "Clear", JOptionPane.YES_NO_OPTION);
        if(btnClear == 0)
        {
            chkJujutsuKaisen.setSelected(false);
            chkHorimiya.setSelected(false);
            chkKimetsunoYaiba.setSelected(false);
            chkShingekinoKyojin.setSelected(false);
            chkBNHA.setSelected(false);
            chkHaikyuu.setSelected(false);
            chkKemonoJihen.setSelected(false);
            chkGakuenBabysitter.setSelected(false);
            txtJujutsuKaisen.setText("0");
            txtHorimiya.setText("0");
            txtKimetsunoYaiba.setText("0");
            txtShingekinoKyojin.setText("0");
            txtBNHA.setText("0");
            txtHaikyuu.setText("0");
            txtKemonoJihen.setText("0");
            txtGakuenBabysitter.setText("0");
            txtJujutsuKaisen.setEditable(false);
            txtHorimiya.setEditable(false);
            txtKimetsunoYaiba.setEditable(false);
            txtShingekinoKyojin.setEditable(false);
            txtBNHA.setEditable(false);
            txtHaikyuu.setEditable(false);
            txtKemonoJihen.setEditable(false);
            txtGakuenBabysitter.setEditable(false);
            rdbCash.setSelected(false);
            rdbDebit.setSelected(false);
            rdbGopay.setSelected(false);
            lblBayar0.setText("Rp.0");
            lblCaraBayar.setText("Cara Bayar");
            
            JOptionPane.showMessageDialog(this, "Clear."); 
        }
          else
        {
            JOptionPane.showMessageDialog(this, "Your data are safe.");         
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void rdbCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCashActionPerformed

    private void rdbGopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbGopayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbGopayActionPerformed

    private void txtHorimiyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorimiyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorimiyaActionPerformed

    private void txtKimetsunoYaibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKimetsunoYaibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKimetsunoYaibaActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
                
        boolean lDataOke = true;
       
        if(chkJujutsuKaisen.isSelected()&& txtJujutsuKaisen.getText() == " ")
            lDataOke = false;
        if(chkHorimiya.isSelected()&& txtHorimiya.getText() == " ")
            lDataOke = false;
        if(chkKimetsunoYaiba.isSelected()&& txtKimetsunoYaiba.getText() == " ")
            lDataOke = false;
        if(chkShingekinoKyojin.isSelected() && txtShingekinoKyojin.getText() == " ")
            lDataOke = false;
        if(chkBNHA.isSelected() && txtBNHA.getText() == " ")
            lDataOke = false;
        if(chkKemonoJihen.isSelected() && txtKemonoJihen.getText() == " ")
            lDataOke = false;
        if(chkHaikyuu.isSelected() && txtHaikyuu.getText() == " ")
            lDataOke = false;
        if(chkGakuenBabysitter.isSelected() && txtGakuenBabysitter.getText() == " ")
            lDataOke = false;
        if(!lDataOke){
        } 
            else {
            
            int nJujutsuKaisen = Integer.parseInt(txtJujutsuKaisen.getText());
            int nHorimiya = Integer.parseInt(txtHorimiya.getText());
            int nKimetsunoYaiba = Integer.parseInt(txtKimetsunoYaiba.getText());
            int nShingekinoKyojin = Integer.parseInt(txtShingekinoKyojin.getText());
            int nBNHA = Integer.parseInt(txtBNHA.getText());
            int nKemonoJihen = Integer.parseInt(txtKemonoJihen.getText());
            int nHaikyuu = Integer.parseInt(txtHaikyuu.getText());
            int nGakuenBabysitter = Integer.parseInt(txtGakuenBabysitter.getText());
            //hitung total
            int nTotal = (5000*nJujutsuKaisen) + (2000*nHorimiya) + (3000*nKimetsunoYaiba) + (4500*nShingekinoKyojin)  + (5000*nBNHA)  + (4000*nHaikyuu)  + (3000*nKemonoJihen) + (2500*nGakuenBabysitter);
            
            lblBayar0.setText("Rp."+nTotal);
            
            JOptionPane.showMessageDialog(this, "Thanks for coming! \n You have pay " + nTotal + " rupiah. \n Don't forget to go to the cashier. \n Have a great day!");
            
            //bagian ini untuk menampilkan cara bayar
            if(rdbGopay.isSelected())
                lblCaraBayar.setText(rdbGopay.getActionCommand());
            if(rdbDebit.isSelected())
                lblCaraBayar.setText(rdbDebit.getActionCommand());
            if(rdbCash.isSelected())
                lblCaraBayar.setText(rdbCash.getActionCommand());
            }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void chkKimetsunoYaibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKimetsunoYaibaActionPerformed
        // TODO add your handling code here:
        if(chkKimetsunoYaiba.isSelected()){
            txtKimetsunoYaiba.setEditable(true);
            txtKimetsunoYaiba.setText("1");
        } else{
          txtKimetsunoYaiba.setEditable(false);
          txtKimetsunoYaiba.setText("0");
        }
    }//GEN-LAST:event_chkKimetsunoYaibaActionPerformed

    private void chkShingekinoKyojinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShingekinoKyojinActionPerformed
        // TODO add your handling code here:
        if(chkShingekinoKyojin.isSelected()){
            txtShingekinoKyojin.setEditable(true);
            txtShingekinoKyojin.setText("1");
        } else{
          txtShingekinoKyojin.setEditable(false);
          txtShingekinoKyojin.setText("0");
        }
    }//GEN-LAST:event_chkShingekinoKyojinActionPerformed

    private void rdbDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbDebitActionPerformed

    private void chkKemonoJihenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKemonoJihenActionPerformed
        // TODO add your handling code here:
        if(chkKemonoJihen.isSelected()){
            txtKemonoJihen.setEditable(true);
            txtKemonoJihen.setText("1");
        } else{
          txtKemonoJihen.setEditable(false);
          txtKemonoJihen.setText("0");
        }
    }//GEN-LAST:event_chkKemonoJihenActionPerformed

    private void chkGakuenBabysitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGakuenBabysitterActionPerformed
        // TODO add your handling code here:
        if(chkGakuenBabysitter.isSelected()){
            txtGakuenBabysitter.setEditable(true);
            txtGakuenBabysitter.setText("1");
        } else{
          txtGakuenBabysitter.setEditable(false);
          txtGakuenBabysitter.setText("0");
        }
    }//GEN-LAST:event_chkGakuenBabysitterActionPerformed

    private void chkHaikyuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHaikyuuActionPerformed
        // TODO add your handling code here:s
        if(chkHaikyuu.isSelected()){
            txtHaikyuu.setEditable(true);
            txtHaikyuu.setText("1");
        } else{
          txtHaikyuu.setEditable(false);
          txtHaikyuu.setText("0");
        }
    }//GEN-LAST:event_chkHaikyuuActionPerformed

    private void chkBNHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBNHAActionPerformed
        // TODO add your handling code here:
        if(chkBNHA.isSelected()){
            txtBNHA.setEditable(true);
            txtBNHA.setText("1");
        } else{
          txtBNHA.setEditable(false);
          txtBNHA.setText("0");
        }
    }//GEN-LAST:event_chkBNHAActionPerformed

    private void txtBNHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBNHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBNHAActionPerformed

    private void txtKemonoJihenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKemonoJihenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKemonoJihenActionPerformed

    private void txtGakuenBabysitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGakuenBabysitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGakuenBabysitterActionPerformed

    private void txtHaikyuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHaikyuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHaikyuuActionPerformed

                                     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        bookrent view = new bookrent();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookrent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookrent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookrent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookrent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookrent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkBNHA;
    private javax.swing.JCheckBox chkGakuenBabysitter;
    private javax.swing.JCheckBox chkHaikyuu;
    private javax.swing.JCheckBox chkHorimiya;
    private javax.swing.JCheckBox chkJujutsuKaisen;
    private javax.swing.JCheckBox chkKemonoJihen;
    private javax.swing.JCheckBox chkKimetsunoYaiba;
    private javax.swing.JCheckBox chkShingekinoKyojin;
    private javax.swing.JLabel lblBayar0;
    private javax.swing.JLabel lblCaraBayar;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNamaProgram;
    private javax.swing.JPanel pnlCaraBayar;
    private javax.swing.JPanel pnlInti;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JRadioButton rdbCash;
    private javax.swing.JRadioButton rdbDebit;
    private javax.swing.JRadioButton rdbGopay;
    private javax.swing.JTextField txtBNHA;
    private javax.swing.JTextField txtGakuenBabysitter;
    private javax.swing.JTextField txtHaikyuu;
    private javax.swing.JTextField txtHorimiya;
    private javax.swing.JTextField txtJujutsuKaisen;
    private javax.swing.JTextField txtKemonoJihen;
    private javax.swing.JTextField txtKimetsunoYaiba;
    private javax.swing.JTextField txtShingekinoKyojin;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
